### ISSUE TITLE
Some error codes in running, I was hoping you could help?

### ISSUE THREAD

**Issue by classicrob** [DeLub/bear-backlinks#1]
Hi! Thank you so much for making this program, it'll really make Bear far more useful for me for writing my hypertext nonlinear book. I tried running the code and ended up coming up with this error. Any suggestions? 
![image](https://user-images.githubusercontent.com/46608303/85573185-e6f8ce80-b5f2-11ea-8709-1909604c25c9.png)

**Comment by DeLub** [comment]
Hi,

Which version of Python are you using? (I was aiming for python 2.7 as this is the default MacOS version)

**Comment by DeLub** [comment]
I'll close this issue for now. If you need further assistance, let me know.
